// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI7PBYvRlTw-xYFf3Epyq3_HkYgVDPaZk',
    appId: '1:885748631896:web:7d6b9be28df240de233d2d',
    messagingSenderId: '885748631896',
    projectId: 'ecrumedia-f7c49',
    authDomain: 'ecrumedia-f7c49.firebaseapp.com',
    storageBucket: 'ecrumedia-f7c49.firebasestorage.app',
    measurementId: 'G-ZTTNJ60SGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu6TrlbDw8i37U0dDhBpWLElok5lE_V3s',
    appId: '1:885748631896:android:68253375a09a30a9233d2d',
    messagingSenderId: '885748631896',
    projectId: 'ecrumedia-f7c49',
    storageBucket: 'ecrumedia-f7c49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ30Jg5HY5M-D7U1zI0qpJS_jCu1QR6dA',
    appId: '1:885748631896:ios:e27a2c8e62272278233d2d',
    messagingSenderId: '885748631896',
    projectId: 'ecrumedia-f7c49',
    storageBucket: 'ecrumedia-f7c49.firebasestorage.app',
    iosBundleId: 'com.ecrumedia.app.ecrumedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ30Jg5HY5M-D7U1zI0qpJS_jCu1QR6dA',
    appId: '1:885748631896:ios:e27a2c8e62272278233d2d',
    messagingSenderId: '885748631896',
    projectId: 'ecrumedia-f7c49',
    storageBucket: 'ecrumedia-f7c49.firebasestorage.app',
    iosBundleId: 'com.ecrumedia.app.ecrumedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI7PBYvRlTw-xYFf3Epyq3_HkYgVDPaZk',
    appId: '1:885748631896:web:cc833a6d11468851233d2d',
    messagingSenderId: '885748631896',
    projectId: 'ecrumedia-f7c49',
    authDomain: 'ecrumedia-f7c49.firebaseapp.com',
    storageBucket: 'ecrumedia-f7c49.firebasestorage.app',
    measurementId: 'G-5F95ZV8CER',
  );
}
